version: "3.8"

x-loki: &defaultloki
  image: dylanguedes/loki:HEAD-1dc0d97-WIP
  volumes:
  - ./:/opt/loki/
  networks:
  - loki

services:
  loki1:
    <<: *defaultloki
    command: "-config.file=/opt/loki/loki-config.yaml -target=index-gateway"
    ports:
      - 3100:3100

  loki2:
    <<: *defaultloki
    command: "-config.file=/opt/loki/loki-config.yaml -target=index-gateway"
    ports:
      - 3101:3100

  loki3:
    <<: *defaultloki
    command: "-config.file=/opt/loki/loki-config.yaml -target=querier"
    ports:
      - 3102:3100

# Network
networks:
  loki:
