version: "3.8"

x-loki: &defaultloki
  image: grafana/loki:main-d38c208
  volumes:
  - ./:/opt/loki/
  networks:
  - loki

services:
  write-1:
    <<: *defaultloki
    command: "-config.file=/opt/loki/loki-config.yaml -target=write -log.level=debug"
    ports:
      - 3100:3100

  write-2:
    <<: *defaultloki
    command: "-config.file=/opt/loki/loki-config.yaml -target=write -log.level=debug"
    ports:
      - 3101:3100

  write-3:
    <<: *defaultloki
    command: "-config.file=/opt/loki/loki-config.yaml -target=write -log.level=debug"
    ports:
      - 3102:3100

  read-1:
    <<: *defaultloki
    command: "-config.file=/opt/loki/loki-config.yaml -target=read -log.level=debug"
    ports:
      - 3103:3100

  read-2:
    <<: *defaultloki
    command: "-config.file=/opt/loki/loki-config.yaml -target=read -log.level=debug"
    ports:
      - 3104:3100

  read-3:
    <<: *defaultloki
    command: "-config.file=/opt/loki/loki-config.yaml -target=read -log.level=debug"
    ports:
      - 3105:3100

# Network
networks:
  loki:
