version: "3.8"

x-loki: &defaultloki
  image: grafana/loki:2.4.1
  volumes:
  - ./:/opt/loki/
  networks:
  - loki

services:
  # Read-path nodes.
  loki-read1:
    <<: *defaultloki
    command: "-config.file=/opt/loki/loki-config.yaml -target=read"
    ports:
    - 3100:3100

  loki-read2:
    <<: *defaultloki
    command: "-config.file=/opt/loki/loki-config.yaml -target=read"
    ports:
    - 3101:3100

  loki-read3:
    <<: *defaultloki
    command: "-config.file=/opt/loki/loki-config.yaml -target=read"
    ports:
    - 3102:3100

  # Write-path nodes.
  loki-write1:
    <<: *defaultloki
    command: "-config.file=/opt/loki/loki-config.yaml -target=write -ingester.lifecycler.ID=write1"
    ports:
    - 3200:3100

  loki-write2:
    <<: *defaultloki
    command: "-config.file=/opt/loki/loki-config.yaml -target=write -ingester.lifecycler.ID=write2"
    ports:
    - 3201:3100

  loki-write3:
    <<: *defaultloki
    command: "-config.file=/opt/loki/loki-config.yaml -target=write -ingester.lifecycler.ID=write3"
    ports:
    - 3202:3100

  # loki-frontend:
  #   <<: *defaultloki
  #   command: "-config.file=/opt/loki/loki-config.yaml -target=query-frontend"

# Network
networks:
  loki:
