version: "3.8"

x-loki: &defaultloki
  image: grafana/loki:main-49ffe52-amd64
  volumes:
  - ./:/opt/loki/
  networks:
  - loki

services:
  ring:
    <<: *defaultloki
    image: grafana/loki:main-49ffe52-amd64
    command: "-config.file=/opt/loki/loki-config.yaml -target=distributor"
    ports:
      - 3100:3100

  distributor:
    <<: *defaultloki
    image: grafana/loki:main-49ffe52-amd64
    command: "-config.file=/opt/loki/loki-config.yaml -target=distributor"
    ports:
      - 3101:3100

# Network
networks:
  loki:
