global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
    - targets:
      - 'querier:3100'
      - 'index-gateway1:3100'
      - 'index-gateway2:3100'
      - 'index-gateway3:3100'
